# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache2-Protocol-ESMTP
version:      0.01
version_from: lib/Apache2/Protocol/ESMTP.pm
installdirs:  site
requires:
    Apache2::Protocol:             
    Apache2::ServerUtil:           

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
